### ISSUE TITLE
False-positive "invalid ccNumber" when using a valid number

### ISSUE THREAD

**Issue by gustavoramos00** [bendrucker/angular-credit-cards#100]
The following numbers are valid credit card numbers, but an error occurs when using them:
6362970000457013
6062825624254001
5078601912345600019

You can check the numbers in this sites:
http://www.validcreditcardnumber.com/
http://www.freeformatter.com/credit-card-number-generator-validator.html

Thanks

**Comment by bendrucker** [comment]
Please file against [creditcards-types](https://github.com/bendrucker/creditcards-types) with the card types these should match
