### ISSUE TITLE
cc-format novalidate not working in chrome

### ISSUE THREAD

**Issue by bennyp123** [bendrucker/angular-credit-cards#102]
Howdy!
I've got this:
```<input name="cardNumber" 	cc-number cc-format cc-eager-type 	type="text" 	ng-model="card.number" 		ng-show="!card.number" 	focus-if="!card.number"		 novalidate ng-required="boolean"/>```
chrome (mac 49.0.2623.87) and firefox (45.0.1) won't validate the field if I set cc-format (which I'd love to do cause it's so slick) safari will, and so will vivaldi(b3)
They say "Please match the requested format" on the cc field

**Comment by bennyp123** [comment]
I also get this error when inputting this AMEX testing number: `378282246310005 ` with a space at the end, even if cc-format is not used.

**Comment by bendrucker** [comment]
Clarified in the docs that that attribute belongs on the form rather than the input

**Comment by bennyp123** [comment]
That did 'er. thanks!
