### ISSUE TITLE
cc-number allows extra numbers

### ISSUE THREAD

**Issue by jensengar** [bendrucker/angular-credit-cards#103]
![ccnum](https://cloud.githubusercontent.com/assets/6035507/14096417/b13cebb8-f536-11e5-89a2-392e8a7a59b1.png)

This happened recently. It leads me to believe it has something to do with an angular version perhaps. This is what my template looks like:

`<input id="creditCard" type="text" name="card" required cc-number cc-format novalidate ng-model-options="{updateOn: 'blur'}" ng-model="card.number"/>`

**Comment by bendrucker** [comment]
Visa cards can be up to 19 digits (+3), are you sure you aren't seeing that?

**Comment by jensengar** [comment]
My apologies then. I thought all cards were 16. Thanks!
