### ISSUE TITLE
Disover card number validates as Maestro

### ISSUE THREAD

**Issue by WesleyE** [bendrucker/angular-credit-cards#104]
Hi,

I'm trying out some of the credit card test numbers but there is an issue with Discover and Maestro numbers:

In the new version (with added meastro validation), and Discover number (6011111111111117 for example) shows up as the wrong card. In the demo version at http://embed.plnkr.co/uE47aZ/preview, it does show up correctly as a Discover card.

I've tried numbers from these sites:

http://www.getcreditcardnumbers.com/ https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm

Is this a known issue?

**Comment by bendrucker** [comment]
Credit cards are weird ;)

Did some research on this a while back and found credible source indicating that the number you have above (common test Discover number) is not actually in the valid Discover range.

https://www.barclaycard.co.uk/business/files/Ranges-and-Rules-February-2016.pdf

I chose to validate correct with more complex regexes vs maintaining compatibility with processor-listed test numbers which inherently don't hit the payment network and therefore don't actually have to be in the real-world range.

**Comment by WesleyE** [comment]
Ah, thanks for the quick and great answer!
