### ISSUE TITLE
Make all validators return true for empty inputs

### ISSUE THREAD

**Issue by jdforsythe** [bendrucker/angular-credit-cards#106]
In my use case, I use the directive to validate initial payment data input, where all fields are obviously required. However I also need to use it when a user needs to update their payment information. In many cases the account number remains the same and only the expiration date gets updated. The account number won't be populated into the field when editing, because you never want to show the full number again, so the field is left empty. This `ccNumber` validation fails when the field is empty.

I think it's best that the validation doesn't fail if the model is empty. This would allow using the same validation for editing an existing number, as in the use case I've presented. The original behavior can still be achieved by simply including `ng-required="true"` on the input field.

**Comment by bendrucker** [comment]
My position in the past has been that anything that's not a valid card number should be invalid. I just went and reviewed Angular's own built in validators and they check for emptiness:

```js
return ctrl.$isEmpty(value) || customValidation
```

In the spirit of consistency I'll go ahead and implement that here as well.
