### ISSUE TITLE
New Mastercards can begin with a 2 - eager loading is not picking this up

### ISSUE THREAD

**Issue by davidleverage** [bendrucker/angular-credit-cards#108]
Your regular expressions for mastercard need to be updated:

exports.masterCard = new Type('MasterCard', {
  pattern: /^5[1-5]\d{14}$/,
  eagerPattern: /^5[1-5]/
})

"MasterCard has announced that their BIN ranges are being expanded to include BINs beginning with a "2" effective October 2016.

The new BINs (222100-272099) must be accepted as MasterCard transactions and treated in the same manner as the existing MasterCard 5 series BINs (510000-559999)."

**Comment by bendrucker** [comment]
Please file this in bendrucker/creditcards-types, happy to review it there. For range updates I ask for links to documentation from a card issuer over pull quotes to make sure I get the range right.
