### ISSUE TITLE
Discover Card Entry

### ISSUE THREAD

**Issue by mr-White** [bendrucker/angular-credit-cards#111]
This seems to only happen with Discover Card (type: 'Discover')

When entering this: 6011000990139424

As I type 6011, it works, but when I enter the first subsequent zero, the formatting does not kick in till I enter the second zero, which then places the cursor before the second zero.

**Comment by drKnoxy** [comment]
second this, i have a fix though.

**Comment by bendrucker** [comment]
Awesome, looking forward to a PR!
