### ISSUE TITLE
Create minified version for cdnjs

### ISSUE THREAD

**Issue by hunt3ri** [bendrucker/angular-credit-cards#113]
Hi Ben
Have you thought about creating a build for cdnjs.  We want to use the lib in production but would like to use a minified version, ideally hosted on a cdn.  Otherwise we're going to have to minify and host ourselves.

I'm happy to help to create the minified version if you're interested.

Thanks
Iain

**Comment by bendrucker** [comment]
Hey there,

I don't release minified code so you should handle that yourself. That choice is motivated by my own habits. Since I haven't included libraries via script tags and CDNs in years I chose to not publish them when I started doing open source.
