### ISSUE TITLE
Working with angular-messages

### ISSUE THREAD

**Issue by 32teeths** [bendrucker/angular-credit-cards#117]
I am using angular-credit-cards in my project for which I have the following template 

```  
<md-input-container class="margin-bottom-0" flex>
              <label>Card Number</label>
              <input name="cardnumber" type="text" cc-number ng-required="true" ng-model="payment.creditcard.number" placeholder="Enter credit card number">
              <div ng-messages="creditForm.cardnumber.$invalid">
                <div ng-message="required">This is required.</div>
                <!-- <div ng-message="ccNumber">Not a valid Credit Card</div> -->
              </div>
            </md-input-container>
```
Since the directive adds a custom validator , I need that to be specified as the value for ng-message , But  I am not able to find it . I tried using `ccNumber` but that is not working , Please help . 

Thanks .

**Comment by bendrucker** [comment]
See the docs for ngMessages and swap $invalid for $error

https://docs.angularjs.org/api/ngMessages/directive/ngMessages

**Comment by marcgetqd** [comment]
hey @bendrucker 

I have everything working, just can't figure out how to display an error in the `ccExpYear` and `ccExpMonth` fields if there is a letter entered. Displays an error on `ccCvc` if a letter is entered.

I have the following:

```
<div ng-messages="bInfoForm.ccExpY.$error">
    <div ng-message="required">Expiry year is required</div>
    <div ng-message="ccExpYear">Expiry year is invalid</div>
</div>
```

Tried to add `<div ng-message="pattern">Expiry year is invalid</div>` with no results.

Thanks.
