### ISSUE TITLE
Getting WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by jcao02** [bendrucker/angular-credit-cards#119]
This happens when I try to load the module like this:

```
var angular = require('angular');
require('angular-credit-cards');

// Application Setup
angular.module('my-app', ['credit-cards'])
```

I think the problem is in [this line](https://github.com/bendrucker/angular-credit-cards/blob/master/src/index.js#L3) where angular is required `var angular = require('angular')` (actually I removed the line and the WARNING disappeared) 

**Note**: I installed the module with [jspm](http://jspm.io/), so I'm loading the module from `src/index.js`  instead of `release/angular-credit-cards.js` because jspm uses npm installation which doesn't include the `release` directory.

**Comment by bendrucker** [comment]
Not sure how jspm installs/manages modules. It should be de-duping.

**Comment by jcao02** [comment]
Solved. I'll leave my solution here in case anyone else is having this problem:

The thing is that `release` directory is never fetched through `npm`, so there's only `src/index.js` as main file to load the module. However, jspm allows you to fetch directly from github using `github` registry, which is what I needed because that way I'd get `release/angular-credit-cards.js` file. Also, I overrode the default `package.json` using jspm to make `release/angular-credit-cards.js` the module's `main` . This is the exact command:

```
jspm install github:bendrucker/angular-credit-cards -o "{main: 'release/angular-credit-cards.js', dependencies : { ap: 'npm:ap@~0.2.0', 'cast-array': 'npm:cast-array@~1.0.1', creditcards: 'npm:creditcards@~2.1.0', 'function-bind': 'npm:function-bind@~1.0.2'}}"
```

The `dependencies` key in the object is to make the module fetch them from `npm` and install them in case they're missing.

Anyway, [here](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm)'s jspm documentation to override the module default configuration.

**Comment by bendrucker** [comment]
That works. I was assuming jspm tried to mimic normal npm behavior so things written in CommonJS would work.
