### ISSUE TITLE
Feature request: cc-exp single field with entry detection

### ISSUE THREAD

**Issue by cozzbie** [bendrucker/angular-credit-cards#127]
Will love to use the cc-exp with one input field in the MM/YY format that formats the input as I enter it inserting a / after the first two digits entered for month and the stops after two digits entered for year.

**Comment by bendrucker** [comment]
I've built this before:

https://github.com/bendrucker/virtual-credit-cards/blob/master/expiration.js

Not a priority for me to add it here but I'd be happy to consider a PR

**Comment by cozzbie** [comment]
Okidoks then. Will take a look at your implementation and TRY to rework. Seems "simple" enough. Just kidding, that looks like some really complex stuff. :D
