### ISSUE TITLE
cc-format and cc-number do not work in unison.

### ISSUE THREAD

**Issue by CormacdeBarra** [bendrucker/angular-credit-cards#128]
Hi,

cc-format and cc-number do not work together. If cc-number fails validation then the formatting does not happen. 

For e.g if you type in 1111111111111111, which is not a valid card number. However this will not format into 1111 1111 1111 1111 as it should.

If I type in a card that starts with a valid number like 2 or 5 it does format correctly. It's very inconsistent behavior. It can be observed in your demo plunker.

Thanks.

**Comment by bendrucker** [comment]
> However this will not format into 1111 1111 1111 1111 as it should.

The library assumes that's not true. Each card type has it's own formatting. Many use the 4x4 format but others, including Amex uses a different one. Unless you get a partial match you won't get formatting because there's no default format.

**Comment by CormacdeBarra** [comment]
Thanks for the quick reply. However I believe it should have a default format. 4*4 seems like the obvious choice for the default format as the majority of cards use it. Validation and display should not be tied together in my view.
