### ISSUE TITLE
Custom validation

### ISSUE THREAD

**Issue by costea93** [bendrucker/angular-credit-cards#131]
Hey guys, it's possible to add new kind of validation for card number? for example:

XXXX XXXX XXXX 3456 to be valid!

**Comment by bendrucker** [comment]
Not at the moment, happy to keep this issue open about it though if I have time to work on it. I can add the ability to add new types w/ a provider.

**Comment by kbala** [comment]
@bendrucker Can you suggest any quick way?

**Comment by costea93** [comment]
@bendrucker, man any idea on how to do that that will be great 👍

**Comment by owlyowl** [comment]
Yeah it would be awesome to add extra validation when running through test card sequences like 4222 2222 2222 2222 etc so you could define a list of test cards that will pass

**Comment by bendrucker** [comment]
Closing based on inactivity, I'm not planning on taking this on
