### ISSUE TITLE
cc-exp-year - entering "2018" gives a value of "202018"

### ISSUE THREAD

**Issue by oodavid** [bendrucker/angular-credit-cards#135]
Using the following:

`<input type="number" name="myCardExpYear"  ng-model="newCard.exp_year"  cc-exp-year  ng-required="true" placeholder="YY">`

It's possible to enter "2018" as the year, which yields a value of "202018"

**Comment by bendrucker** [comment]
The directive adds `maxlength="2"`, how is it possible to enter 4 characters?

**Comment by oodavid** [comment]
Ahh, it's a mismatch - apparently `maxlength` doesn't apply when
`type="number"` instead I guess we need min/max.


*Kind Regards,*
*David King*

*Tel: +44(0)7939273963*

*Site: oodavid.com <http://oodavid.com/>*

**Comment by oodavid** [comment]
Ahh, it's a mismatch - apparently `maxlength` doesn't apply when `type="number"` instead I guess we need min/max.

**Comment by bendrucker** [comment]
That's called out as not recommended in the docs: https://github.com/bendrucker/angular-credit-cards#cc-exp
