### ISSUE TITLE
Diners club

### ISSUE THREAD

**Issue by returnvoid** [bendrucker/angular-credit-cards#138]
Hi 

I'm trying to validate Diners Club number provided by Stripe https://stripe.com/docs/testing#cards (3056 9309 0259 04) but it's not working. I guess the right group pattern will be:

`groupPattern: /(\d{1,4})?(\d{1,4})?(\d{1,4})?(\d{1,2})?/`

thanks

**Comment by bendrucker** [comment]
Hi, take a look at some previous issues about Stripe's invalid test cards, I choose to do strict validation in the interest of validating real cards:

https://github.com/bendrucker/angular-credit-cards/issues/134

If you think there's a genuine card that won't validate feel free to report here:

https://github.com/bendrucker/creditcards-types
