### ISSUE TITLE
Numerical Keyboard is not showing up on Android

### ISSUE THREAD

**Issue by ShadowVariable** [bendrucker/angular-credit-cards#146]
Running into an issue where the inputs with the credit-cards bindings are working fine and displaying the numerical keyboard on iOS but not Android.

**Comment by bendrucker** [comment]
Android does not support the [numeric pattern](https://github.com/bendrucker/numeric-pattern). I'm not an Android users so I don't pay super close attention to any of its behavior. 

The internet is unclear on whether there's a well-supported method:

http://stackoverflow.com/questions/18998732/how-to-open-a-number-pad-on-android-chrome-with-input-type-text
http://stackoverflow.com/questions/35437429/force-numeric-input-when-viewing-website-on-android-ios

If you do the research and come back with screenshots and corresponding HTML snippets I'd be happy to add special behavior using [is-android](https://github.com/bendrucker/is-android).

**Comment by ShadowVariable** [comment]
Hmm ok, I opted to trigger the ionic soft keyboard on click and that seems to do the trick. Thanks.

**Comment by bendrucker** [comment]
Sounds good!
