### ISSUE TITLE
Release version not sent with npm version?

### ISSUE THREAD

**Issue by aralko** [bendrucker/angular-credit-cards#147]
Hi, the release folder/build is not included with the rest of the code with the npm version. Is there reasoning for this?

**Comment by bendrucker** [comment]
That's correct. I generally don't provide UMD builds and other artifacts via npm and prioritize bundler users.

**Comment by szimek** [comment]
@bendrucker Is there any reason to not include these files in npm package? It's just a matter of adding `release/*.js` to `files` prop in `package.json` and would help a lot people who are stuck with grunt or gulp in their build pipelines.

**Comment by bendrucker** [comment]
I don't compile code for any npm package I publish. I've authored >400 modules and this is just one of many variants of "please change your workflow/code to support my build tool." 

This package has dependencies that manage critical functionality (the credit card validation and parsing guts). Making a UMD build the `main` module is unfriendly users with modern dependency/build toolchains. People who are just using npm as a downloader for self-contained scripts and manually specifying every dependency path can depend on the git repo directly.
