### ISSUE TITLE
Test card numbers showing wrong card type

### ISSUE THREAD

**Issue by kbrec85** [bendrucker/angular-credit-cards#154]
We're implementing and testing stripe and I'm seeing the stripe test card numbers for JCB and the 601111 discover cards coming through as the wrong card type. Am I doing something wrong in my implementation or are those test cards numbers odd?

https://stripe.com/docs/testing

**Comment by bendrucker** [comment]
There are lots of past issues about invalid test cards, feel free to look through those for more details. Short answer is that Stripe is wrong here.
