### ISSUE TITLE
Guess card type with partial number (eager type detection)

### ISSUE THREAD

**Issue by owlyowl** [bendrucker/angular-credit-cards#16]
Detect card type faster for the purposes of user feedback. Examples of this feature can be seen here: http://tamas.io/custom-angularjs-filter-to-determine-credit-card-type/

And a demo of functionality:https://gumroad.com/l/demo

Press the "I want this" button and start typing cc number into the supplied field and note the icon highlight based on cc type

**Comment by bendrucker** [comment]
https://github.com/bendrucker/creditcards/issues/4 will create the underlying method needed to do this. Just need to decide what the API will look like. Options would include generating a separate property, e.g. `$ccEagerType` or allowing an attribute to switch type checking to eager-mode (e.g. `<input cc-number cc-eager-type ng-model="card.number" />`). I'm leaning strongly towards the former.

**Comment by owlyowl** [comment]
I think the former works well

**Comment by bendrucker** [comment]
Went with a blend of both. You have to opt into this by adding the `cc-eager-type` attribute. But it uses a new property so strict typing works the same way it currently does.

**Comment by owlyowl** [comment]
Hi Ben,
Thanks so much for introducing this I really appreciate it. Had a look at
the changelog I like your implementation.

Thanks,
Tom

On 19 February 2015 at 11:48, Ben Drucker <notifications@github.com> wrote:

> Went with a blend of both. You have to opt into this by adding the
> cc-eager-type attribute. But it uses a new property so strict typing
> works the same way it currently does.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bendrucker/angular-credit-cards/issues/16#issuecomment-74980437>
> .
>



-- 
Tom Fulcher
Creative Designer and Developer

[image: Envoy]

Envoy Advanced Technologies Pty Ltd
Level 1, 194 Miller St, North Sydney NSW 2060

Mobile Apps | Software Development | Custom Applications | Fully Managed
Hosting

http://www.envoyat.com | m: 0403 316 714 | p: +61 2 8097 7328 | skype:
thomen12

---------------------------------------------------------------------------------
This email and any attachment is only intended for the use of the
individuals or entities to whom it is addressed and may contain
confidential, privileged information. If the reader of this information is
not the addressee, please be advised that any dissemination, distribution
or copying of this email is strictly prohibited. If you receive this
communication in error, please return this email to Envoy Advanced
Technologies at the above email address and delete it from your files.
Thank you.
