### ISSUE TITLE
cc-number validation

### ISSUE THREAD

**Issue by Med-All** [bendrucker/angular-credit-cards#161]
When I will add code below to the demo code

```
  <input type="text" ng-model="card.number" name="cardNumber" cc-number cc-eager-type />
<p ng-show="ccForm.cardNumber.$invalid && ccForm.cardNumber.$ccEagerType">
  Looks like you're typing a {{paymentForm.cardNumber.$ccEagerType}} number!
</p>
```
It let me to use letters not throwing an error above when `cardNumber` is invalid.

**Comment by bendrucker** [comment]
I don't know what the question here is, doesn't sound like this is a bug report though. Feel free to give me a specific question if you need support.

**Comment by Med-All** [comment]
When I was added a code from your example

```
  <input type="text" ng-model="card.number" name="cardNumber" cc-number cc-eager-type />
<p ng-show="ccForm.cardNumber.$invalid && ccForm.cardNumber.$ccEagerType">
  Looks like you're typing a {{paymentForm.cardNumber.$ccEagerType}} number!
</p>
```

to the demo code here http://embed.plnkr.co/uE47aZ/preview 

I was able to type in letters into the cc-field without throwing error message. 

Question is how I can display `Invalid CC number` message when the field is required but CC number was removed.
