### ISSUE TITLE
cc-exp and required message

### ISSUE THREAD

**Issue by Med-All** [bendrucker/angular-credit-cards#162]
Example:

```
<input type="text" ng-model="card.exp_year" cc-exp-year ng-required="true" class="form-control" placeholder="YY" id="ccExpYY" name="ccExpYY" ng-class="{red: ccForm.ccExpYY.$invalid && (ccForm.$submitted || ccForm.ccExpYY.$touched)}" />

<div ng-messages="ccForm.ccExpYY.$error" ng-if="ccForm.ccExpYY.$invalid && (ccForm.$submitted || ccForm.ccExpYY.$touched)" class="validation-alert" role="alert">
<div ng-message="required">This field is required</div>
<div ng-show="(ccForm.ccExpYY.$invalid  &&  ccForm.ccExpYY.$viewValue != '')">Expiration year is invalid</div>
</div> 
```

When fields if filled out and then value was removed field will be highlighted but message for a required field is not displayed.

**Comment by bendrucker** [comment]
Hey man, please don't keep opening new issues like this. I know Angular form validation is a broad topic. Please read the code and submit a PR if you think the behavior is unclear or wrong.

**Comment by Med-All** [comment]
@bendrucker Pull request for what? I have expected that default behaviors like `ng-required="true"`  and `ng-message="required"` are going to work. If not that is a bug as is failing on a default behaviors for AngularJS
