### ISSUE TITLE
[FIX] Temporary fix for ngRequired directive case

### ISSUE THREAD

**Issue by Med-All** [bendrucker/angular-credit-cards#163]
It is a temporary workaround for `ngRequired` directive case used in a combination with `cc-number`, `cc-cvc` or `cc-exp` and related to issues #161 and #162 when the field was `$touched` but nothing was typed in that field. Acceptance criteria in that case is to display only Required message but not Invalid message (any value wasn't provided yet).

To have it resolved, without editing mine code, is to set initial value for mentioned above fields. Example below:

`ng-init="card.number=''"`

then to use it with a combination below to display proper message

```
<span ng-show="(form.input.$error.required || form.input.$error.parse) &&  form.input.$viewValue == ''">Required entry</span>
<span ng-show="form.input.$invalid &&  form.input.$viewValue != ''">Entry is invalid</span>
```

I think it will be good to have it mentioned somewhere in a documentation until it will be fixed permanently in the code.

**Comment by bendrucker** [comment]
_Please_ stop opening new issues. I won't ask again. I'm having a lot of trouble understanding your English and I still don't understand what the problem is and whether it's actually a bug or you're just running into behavior in ngModelController that you don't understand. 

If you'd like to submit a PR for review I'm happy to work with you. A failing test is the way to move this forward.

**Comment by Med-All** [comment]
@bendrucker I'm so sorry for you that you don't understand my English or at least try to understand what other person is trying to hand on.

I have described all what I have found not working as I and others are expecting in case using of `ngRequired` directive with your code.  And I'm not going to write here anymore because it is useless when code owner is a rude person.

**Comment by bendrucker** [comment]
Open source is a volunteer activity. If someone cares to fix this I'm always willing to work through PRs. Even just a failing test would be helpful. I don't use Angular these days and don't want to give the impression that I have time to sort through run-on issues. This, #161, and #162 are not how I'm willing to engage on this project or any of the hundreds of others I maintain at this point.
