### ISSUE TITLE
ng-model-options ignored?

### ISSUE THREAD

**Issue by MathewWoodhall** [bendrucker/angular-credit-cards#164]
On my cc-number input I have the following...

ng-model-options="{ updateOn: 'default blur', debounce: { default: 1500, blur: 0 } }"

This works nicely for my required and minlength validation, there is a delay between typing and the field becoming invalid/valid.

But if the ccNumber is invalid, there is no delay. The field becomes invalid instantly, which isn't ideal. Is this not supported? Or is there a workaround?

Thanks.

**Comment by blakbarn** [comment]
I am having the same issue. Why was this issue closed?
