### ISSUE TITLE
Issue - CC input in google chrome Android Mobile

### ISSUE THREAD

**Issue by nano1313** [bendrucker/angular-credit-cards#165]
When typing credit card number example 4111  5513 ... . After type 4111 and then 5. 
Cursor position is behind 5. When the expected should be the cursor be at the last position of the string.

**Comment by bendrucker** [comment]
Try https://github.com/bendrucker/angular-credit-cards/pull/143 and see if works, I could see about adding a test and merging it

**Comment by rahmanroman** [comment]
Confirmed that android chrome works much more better with PR #143. Cursor position is fully predictable. Please-please-please merge it for new release version.

**Comment by bendrucker** [comment]
Hey that’s helpful but a test would be more helpful. I’ll work on this project sometime in the next two weeks and the way to contribute at this point and guarantee I merge it is trying to add a test.
