### ISSUE TITLE
Problem with validating DISCOVER cards

### ISSUE THREAD

**Issue by lordmilutin** [bendrucker/angular-credit-cards#166]
I have  problem with validating DISCOVER cards, it keeps asking to match requested format.

I have tried: (stripe test cards)
6011 0009 9013 9424
6011 1111 1111 1117 
And even one real one, same thing.

I am using "angular-credit-cards": "^3.1.4" installed from bower

**Comment by bendrucker** [comment]
There are countless issues about how Stripe's cards aren't strictly valid. I'll leave you to search for those if you're interested. A real credit card is definitely interesting though.

The type definitions are provided here and are assembled from card issuer documentation:

https://github.com/bendrucker/creditcards-types

If you have a real card that's not matched please try to add the pattern there and I'll try to reconcile it with the documented ranges and figure out whether the docs are wrong or I just made a mistake in translating them to regexes.
