### ISSUE TITLE
Angular import overwrites angular global with webpack

### ISSUE THREAD

**Issue by blove** [bendrucker/angular-credit-cards#167]
Using webpack to build an AngularJS application with angular-credit-cards throw an exception because src/index.js overwrites the global `angular` variable.

# Steps to reproduce

First, install the module using npm or yarn:

`$ yarn add angular-credit-cards`

If you're starting a new project, you'll need to install all of the dependencies:

`$ yarn add angular angular-credit-cards creditcards ts-loader typescript webpack`
`$ yarn add @types/angular @types/node --dev`

Then, create a webpack.config.js:

```
var path = require("path");
var webpack = require("webpack");

module.exports = {
  "context": path.resolve(__dirname, "./"),
  "devtool": "source-map",
  "entry": "./js/index.ts",
  "module": {
    "rules": [
      {
        "test": /\.ts$/,
        "use": {
          "loader": "ts-loader"
        }
      }
    ]
  },
  "output": {
      "path": path.resolve(__dirname, "./js/build"),
      "filename": "[name].bundle.js"
  },
  "resolve": {
    "alias": {

      //angular
      "angular": path.resolve(__dirname, "./node_modules/angular/angular"),
      "angular-credit-cards": path.resolve(__dirname, "./node_modules/angular-credit-cards/src/index"),
      "angular-sanitize": path.resolve(__dirname, "./node_modules/angular-sanitize/angular-sanitize"),

    },
    "extensions": [".js", ".ts"]
  }
};
```

Finally, create the index.ts entry point:

```
require("angular");
require("angular-credit-cards");

//start angular application
angular.element(document).ready(function() {
  //module name
  const MODULE_NAME: string = "my-app";

  let app: ng.IModule = angular.module(MODULE_NAME, ['credit-cards']);

  //bootstrap the application
  angular.bootstrap(document, [MODULE_NAME], {
    "strictDi": true
  });
});
```

A simple HTML template to test the bundle:
```
<html>
  <body>
    <script src="./js/build/main.bundle.js"></script>
  </body>
</html>
```

# Exception

Webpack builds the bundle successfully, however, testing in the browser results in the following exception:

```
Uncaught TypeError: angular.module is not a function
    at Object.<anonymous> (index.js:10)
    at __webpack_require__ (bootstrap b624737366a50ca01831:19)
    at Object.<anonymous> (index.ts:2)
    at __webpack_require__ (bootstrap b624737366a50ca01831:19)
    at bootstrap b624737366a50ca01831:62
    at bootstrap b624737366a50ca01831:62
```

# Cause

The cause of the exception is the import in the src/index.js file:

`var angular = require('angular')`

Defining the variable `angular` overwrites the global `angular` variable. This causes the exception above where the global `angular` variable is expected.

# Resolution

Update src/index.js import to:

`require('angular')`

**Comment by bendrucker** [comment]
I disagree, I think this is a problem with your setup, though I admittedly don't have the time to read through too carefully or test it out. Depending on side effects of `require('angular')` is not right, angular is responsible for exporting a value. Why should libraries rely on global variable names instead of treating angular like a well behaved module? I authored Angular's CommonJS support years ago and this is the first time anyone has mentioned a problem like this.

**Comment by blove** [comment]
Fair enough. The application should be refactored to import the specific functions as needed rather than relying on the global angular variable.

I suspect that no one has mentioned this issue because it is likely that few people use a bundler like rollup or webpack with AngularJS, the popularity/usage of AngularJS is declining rapidly, or they are correctly importing the functions exported by angular rather than relying on the global angular variable. I will note that the AngularJS documentation almost exclusively uses the global `angular` variable in their examples.

While this is certainly your call as the author, this PR *should* not break existing usage of this module and only add the feature of supporting the use of the global `angular` variable in projects that use webpack. 🦄
