### ISSUE TITLE
Transposes numbers while typing

### ISSUE THREAD

**Issue by neekers** [bendrucker/angular-credit-cards#169]
On IE11 when you type in a credit card number, it transposes some numbers. This is only in version 3.1.7

**Comment by bendrucker** [comment]
Hi, thanks for reporting. I don't have ready access to IE 11 so I don't plan to work on this. If you're interested in contributing a fix via a PR I'd be happy to have a look!

**Comment by neekers** [comment]
Can you leave this open at least so people know it's a real issue? I might contribute a fix

**Comment by bendrucker** [comment]
No, that's not how I manage my repos. Open issues are a todo list for me or other maintainers, I don't keep tickets open for theoretical contributors to find.

**Comment by neekers** [comment]
This is a TODO, no? IE11 is broken. Or maybe change the readme to remove support for IE11? People should know this script won't work.

**Comment by Naquaduh** [comment]
I created a pull request to address this issue. #170 
This is my first ever PR, so please let me know if I did anything wrong.
