### ISSUE TITLE
cc-number directive initialise causes the input field to have a state of ng-touched and ng-dirty

### ISSUE THREAD

**Issue by owlyowl** [bendrucker/angular-credit-cards#17]
![capture](https://cloud.githubusercontent.com/assets/1916426/6240858/90994440-b768-11e4-94a5-d7a53bf3e675.PNG)
Without the user interacting with the field the default state after the directive initialises is ng-dirty and ng-touched and ng-invalid.

This means if using these classes to determine styles the field would look invalid before the user begins.

**Comment by bendrucker** [comment]
I can't reproduce this and would need an example from you that does in order to move forward.
