### ISSUE TITLE
Angular 4?

### ISSUE THREAD

**Issue by ganeshmuthuvelu** [bendrucker/angular-credit-cards#171]
Is there an angular4 version available ?

**Comment by ganeshmuthuvelu** [comment]
Just noticed from the closed issues that the answer is no  :-(

**Comment by bendrucker** [comment]
Correct. I'm not an Angular user anymore. Contributions are welcome and I'd be happy to support someone who wants to work on a rewrite for what is now essentially a different framework. The real value is in the DOM-independent validation which I actively maintain for anyone who wishes to continue building framework-specific tooling.
