### ISSUE TITLE
Test Card Number 6011 1111 1111 1117 Incorrectly Identified

### ISSUE THREAD

**Issue by edmondchui** [bendrucker/angular-credit-cards#178]
The test credit card number 6011 1111 1111 1117 should be a Discover card number, but got identified as Maestro.

**Comment by edmondchui** [comment]
Base issue filed in `creditcards-types`

https://github.com/bendrucker/creditcards-types/issues/54

**Comment by bendrucker** [comment]
https://github.com/bendrucker/creditcards-types/issues/54#issuecomment-590477992
