### ISSUE TITLE
Can this work with angular > 1.7

### ISSUE THREAD

**Issue by crhistianramirez** [bendrucker/angular-credit-cards#179]
I noticed the package.json has a semver range: 
```
"angular": ">=1.3 <1.7"
```

Is there a known issue in angular 1.7 that prevents this package from being compatible or is it more of a safe upper bound of what is known to work well with the package?

**Comment by bendrucker** [comment]
Hi, it will likely work with later 1.x versions. Happy to relax the version if the tests pass. It will probably not work with later major versions.

**Comment by jason-dimeo-wf** [comment]
Hi Ben. I noticed that the package.json file has the updated angular version, but the NPM package does not. Any way you could push a new build to the NPM repo? Thanks in advance.
