### ISSUE TITLE
link to live demo is broken

### ISSUE THREAD

**Issue by gaboesquivel** [bendrucker/angular-credit-cards#23]
link to live demo in plunkr in readme file is broken

**Comment by bendrucker** [comment]
Looks fine to me. Can you double check?

**Comment by gaboesquivel** [comment]
yeah, it works for me now. I was getting a white page within plnkr...

**Comment by bendrucker** [comment]
Great. Definitely interested in self-hosting a much more involved docs page with examples. Just not something I can commit time to right now.
