### ISSUE TITLE
If value from a model is defined as two digit number, validation fails

### ISSUE THREAD

**Issue by hinok** [bendrucker/angular-credit-cards#26]
Hey Ben,
At the moment I have to store expiration year in my database as two digit number.
I can POST expiration year as 4 digit number but when I make GET, I retrieve that value as two digit number. I know that API could convert two digit number to four digit on GET but at the moment I cannot change anything in API because I don't have access to it.

Now if model value is defined as two digit number, validation of expiration year fails.

To sum up, if I have something like this
```javascript
$scope.myCard = {
    year: 29
    // other props...
};
```

The Value in year input is not set and the whole form is not valid.
Plnkr: http://plnkr.co/edit/t53u0fUfXuyNuY5pCv3Q?p=preview

Simple test which fails

```javascript
it('is valid for this year defined as two digit number retrieved from the model', function() {
      expiration.year = 14;
      $scope.$digest();
      expect(controller.$valid).to.be.true;
});
```

I made a fast fix for that specific case. Here is the commit: https://github.com/hinok/angular-credit-cards/commit/2d23bbb377668e0fd26ed24f8fdc545b90391b09

If you want, I can make a PR.

**Comment by bendrucker** [comment]
I'd rather have something more definite where you have to add an attribute to target models with short years. `attributes.shortYear` would be the natural fit for now. Ultimately I'd rather use `cc-display="(full|short)" cc-parse="(full|short")` where display defaults to short and parse defaults to full. 

I'll take a PR that adds `shortYear` with tests if you need it soon—otherwise I'll try to cut a 3.0 release this weekend with a bunch of updates.

**Comment by hinok** [comment]
Thanks for fast response. I decided to go with different solution at the moment and now I decode strings into four digit number in my angular api service so this is not the problem anymore.
`cc-parse` and `cc-display` are far better than my solution!

**Comment by bendrucker** [comment]
Leaving this open until I get to it. Will incorporate it into the next major release unless someone wants it enough to do a PR.

**Comment by bendrucker** [comment]
Changed my mind on this. Passing in `29` as a model value for the year is wrong and angular-credit-cards shouldn't try to fix that. Casting that data somewhere upstream makes things a lot clearer. You can just grab the year parser and do this in one line:

https://github.com/bendrucker/creditcards#expirationyearparseyear--pad---number
