### ISSUE TITLE
If month and year are defined as string, ccExpMonth and ccExpYear shows different result than ccExp

### ISSUE THREAD

**Issue by hinok** [bendrucker/angular-credit-cards#27]
If month and year are set as strings not numbers, validation is not in sync.

Like
```javascript
myCard = {
    year: '2019',
    month: '10'
  };
```

**ccExpMonth.$valid** and **ccExpYear.$valid** are equal to `false`.
**ccExp.$valid** is equal to `true`.

![screen of plnkr](https://cloud.githubusercontent.com/assets/1313605/7194055/214a7730-e4a9-11e4-97a8-0cd57941a7e7.png)

Plnkr http://plnkr.co/edit/oJluKcoqpdwqufYP0D1q?p=preview

**Comment by bendrucker** [comment]
Sorry for missing this one somehow. Those aren't valid values. Inject `creditcards` and use its parsers directly to cast the values properly.
