### ISSUE TITLE
If cc-format is used, form property is set to $dirty from scratch, even if the user has not entered any value yet

### ISSUE THREAD

**Issue by gastonelhordoy** [bendrucker/angular-credit-cards#30]
The live demo plunker was used to reproduced it. I added cc-format to the card number input and updated the version to the latest one. http://embed.plnkr.co/wXctSM/preview

If you check the inspector, you can see the CSS ng-pristine class is not present but ng-dirty is.

**Comment by gastonelhordoy** [comment]
That was fast, thanks man!

**Comment by bendrucker** [comment]
No problemo
