### ISSUE TITLE
Browser validation error with cc-format

### ISSUE THREAD

**Issue by mjyoung** [bendrucker/angular-credit-cards#31]
I'm using Chrome and get the following tooltip validation message:
'Please match the requested format' 

Any suggestions for how to bypass/override this?

This is my code:
```
<div class="icr-ccard icr-ccard-type-{{cardForm.ccNumber.$ccEagerType | ccLowercase}}">
    <input type="text" ng-model="card.number" cc-number cc-type="cardType" name="ccNumber" cc-eager-type cc-format required>
</div>
```

**Comment by bendrucker** [comment]
Nothing I can do about this, see the docs update for the easy fix
