### ISSUE TITLE
Uncaught TypeError: Cannot read property 'noop' of undefined

### ISSUE THREAD

**Issue by sdornan** [bendrucker/angular-credit-cards#32]
I am attempting to use the most recent version of angular-credit-cards with Angular 1.3.15 using RequireJS (the last of which I'm admittedly a bit new to) and getting the following error when loading my app:

```javascript
Uncaught TypeError: Cannot read property 'noop' of undefined
```

This is occurring within the following block of angular-credit-cards.js:

```javascript
var nullCcExp = {
  setMonth: _angular2['default'].noop,
  setYear: _angular2['default'].noop
};
```

Any ideas?

**Comment by bendrucker** [comment]
Use the UMD release (available on each tag) if you're using RequireJS (AMD). I know it's a tad confusing, but the `requires` are Node-style requires designed for use with Browserify/Webpack and RequireJS won't play nice.

**Comment by sdornan** [comment]
Apologies, but I'm not clear on how to do this. Right now I'm just using the bower package. Is there some alternate UMD bower package?

**Comment by bendrucker** [comment]
Ah, I know what this is. I'm guessing you're bundling with RequireJS and its picking up the `require` calls and screwing with them. There's a way to address this (https://github.com/calvinmetcalf/derequire) but it's going to take me some time to get my build tools updated to support it. Will keep this open until it's addressed.

**Comment by atwright147** [comment]
Will derequire set angular-credit-cards up so that we can use it without require.js entirely?

**Comment by bendrucker** [comment]
That's unrelated. The UMD build is there on tags for people who don't want to use Browserify/Webpack. I'm never going to do a UMD build in master because there's no need for it. This is to resolve a conflict with RequireJS. I've never used RequireJS here or anywhere.

**Comment by lookfirst** [comment]
Just poking my head in here to say... don't waste your time with RequireJS. 

At this point the world is moving towards SystemJS as a shim around ES6 module loading.

**Comment by bendrucker** [comment]
> don't waste your time with RequireJS

Truer words have never been spoken :angel: 

Hoping to get to this fix today so the UMD build is truly universal

**Comment by bendrucker** [comment]
Resolved in the latest. 

> I'm never going to do a UMD build in master because there's no need for it

And by never, I mean a month later :)

**Comment by sdornan** [comment]
Apologies, but I am now getting another RequireJS error.
```javascript
Uncaught TypeError: Cannot read property 'module' of undefined
```

on the line

```javascript
module.exports = angular
  .module('credit-cards', [])
```

I would love to get away from RequireJS but am unfortunately stuck with it for now.

**Comment by sdornan** [comment]
I have

```javascript
shim: {
...
    'angular-credit-cards': {
      deps: ['angular']
    },
...
}
```
defined in my RequireJS config. I would love to get this working as it's the only dependency I'm using in my project that isn't.

**Comment by bendrucker** [comment]
Please try the latest compatibility release for AMD/window global users in release/

**Comment by sdornan** [comment]
I am using the most recent version (2.3.5) and pulling in the release source file:
```javascript
paths: {
...
'angular-credit-cards': '../plugin/angular-credit-cards/release/angular-credit-cards',
...
}
```
