### ISSUE TITLE
Card Number validation failure

### ISSUE THREAD

**Issue by asherstoppard** [bendrucker/angular-credit-cards#34]
I'm getting an issue with card number validation. `4297 1038 5038 2` is passing but doesn't meet the minimum required length of 16.

Is there a check for the minimum length within your working for the Luhn algorithm? I'm happy to add one but just wanted to check that the algorithm was working correctly?

**Comment by asherstoppard** [comment]
Scrub that, adding `ng-minlength="16"` doesn't solve the issue as the spaces account for 3 extra characters.

I'm a little uncomfortable adding `ng-minlength="19"` as it would destroy the validation if the spaces weren't to render correctly.

**Comment by bendrucker** [comment]
This is b/c Visas can technically be as short as 13 chars. Information on issuing ranges, lengths, etc. can be a bit difficult to find. I should definitely be referencing the sources for the info over at https://github.com/bendrucker/creditcards-types.

Open up an issue over there. Visa's probably not issuing 13 digit cards anymore and if we can verify that there are no non-expired 13 digit cards I'll update the regex.

**Comment by asherstoppard** [comment]
Thank you very much for your swift response and help, I'll do some further digging :smile:
