### ISSUE TITLE
Not able to recognize credit cards with number length less than 16 (maestro)

### ISSUE THREAD

**Issue by swapneshk** [bendrucker/angular-credit-cards#35]
In the demo, I am trying Maestro demo number - 5018 0000 0009, which is a valid number, but Its showing invalid and unknown.

Demo Link I am trying - http://embed.plnkr.co/uE47aZ/preview

**Comment by bendrucker** [comment]
This would be solved over at https://github.com/bendrucker/creditcards-types

Please reopen there so it's easier for me to track. I'm going to start compiling and publishing the documentation I'm using to determine the valid range of IINs and lengths for cards. If you can find something showing that the Maestro length range includes 12, please let me know.
