### ISSUE TITLE
Doesn't work with ng-required="false" and cc-number attribute

### ISSUE THREAD

**Issue by geuis** [bendrucker/angular-credit-cards#37]
In my particular case, I need to use ng-required on the input to determine if it should be validated or not. When ng-required="false", the this directive still wants tries to validate the input.

**Comment by bendrucker** [comment]
Sorry but I'm not going to parse the value of `ngRequire` and not validate if it's false. If you can explain your use case in a little more detail I'm happy to help you with a more direct solution.

**Comment by geuis** [comment]
It seems that your module should support the native validation capabilities in Angular. Its odd that if the code is specifically saying, "Don't validate this input" via ng-required="false", that the module is validating anyway.

In my scenario, we only need to validate the credit card field when entering a new card. When editing an existing card, we only send the last 4 digits of the card to the client. Pretty standard.

The same form is used for both creating and editing card data (name, address, number, cvv, etc). When editing an existing card, the number input is not shown and a span is visible with the 'xxxx-xxxx-xxxx-1234' style for the number. This is the situation where your module should respect ng-required="false" because the input is in the form, but is not being used for this interaction. However, your module is still trying to validate a control when its being instructed not to.
