### ISSUE TITLE
Incredibly confusing to install

### ISSUE THREAD

**Issue by bgold0** [bendrucker/angular-credit-cards#38]
Thanks so much for making this. I love what I see but getting it to work is a whole other monster. It'd be so much easier and I feel so many more people would take advantage of this if it was just one JS file that I have to include and then add it to my list of modules.

I'm knew to angular and the "installation" side of this is very confusing if you've never used bower/npm. I've been staring at this page for about 30minutes and will probably just end up using jquery.payments :\

**Comment by bendrucker** [comment]
Sorry, not changing the way I write modules. If you want to use jquery.payments because it's easier to copy and paste, go ahead. Otherwise copy and paste from git tags here like you would from any other repo's master.

**Comment by bendrucker** [comment]
https://github.com/bendrucker/angular-credit-cards/blob/v2.3.2/release/angular-credit-cards.js

**Comment by bendrucker** [comment]
I think you'll be pleased to hear that I'm now committing the release dir to master so it's easier to find if you want to copy and paste.
