### ISSUE TITLE
Auto-select `cardType`

### ISSUE THREAD

**Issue by ruipenso** [bendrucker/angular-credit-cards#48]
What do you think about auto-selecting the `cardType` based on the model passed to `cc-type`?

Since the `cc-type` already validates the number with the type selected we could just use the `cc-type` param in the scope to auto-select it.

I think it would be cool if this was also applied to `cc-eager-type` and have a real-time selection.

I can create a PR if you like the idea:

![credit-card](https://cloud.githubusercontent.com/assets/73298/8618151/5085a56e-2703-11e5-8a8b-af2b4c91584a.gif)

/cc @bendrucker

**Comment by ruipenso** [comment]
This can also be implemented in another way - A new directive `cc-type` applied to the card type `select` that will watch the `$ccType` and/or `$ccEagerType` and update the value.

**Comment by bendrucker** [comment]
Why does the lib need to do anything to help you accomplish this?

**Comment by ruipenso** [comment]
Well, I can implement my own directive to auto-select the card type. But, I think that would be cool to add this behaviour to the lib.

**Comment by bendrucker** [comment]
If I'm clear you want something that works with `<select>`. In which case I'm going to say no, that would be great as a separate library, but doesn't belong in the core.

**Comment by ruipenso** [comment]
Ok. It was just a suggestion.

**Comment by bendrucker** [comment]
Understood, and saying no to lots of ideas is critical to open source. If you make something like this I'd be happy to consider linking it from the readme.

**Comment by ruipenso** [comment]
Sure. I know what it takes to get a maintain a good lib. I'll keep you posted in case of building something on top of this.
