### ISSUE TITLE
can drop minimum angular version to 1.3.14 in bower.json?

### ISSUE THREAD

**Issue by ohjames** [bendrucker/angular-credit-cards#49]
It works just fine for me with angular 1.3.14 but the bower.json states 1.4.0 is the minimum supported version, is that definitely accurate?

If it is, any idea what bugs I might experience? I haven't noticed any so far.

**Comment by bendrucker** [comment]
#47 introduced that. It's wrong, wasn't paying attention to the sneaky first commit when I merged that. Please send a PR updating the semver string to match the package.json and I'll get it fixed:

https://github.com/bendrucker/angular-credit-cards/blob/516df5ea8fb8604e1c34a0833a8a9566312896f7/package.json#L46
