### ISSUE TITLE
Month validation : 1 digit instead of 2

### ISSUE THREAD

**Issue by hugsbrugs** [bendrucker/angular-credit-cards#51]
Hi there and thanks for your great plugin !

I have a problem using your code with Stripe API since Stripe absolutely needs a 2 digits number as a month. With v2.0.0 and v2.2.0 everything went well but with the very last versions (2.3.4 & 2.3.5) I'm getting in trouble. Am I the only one who experience this problem ? Is it something (choose 1 or 2 digits for monthes between 1 and 9) that could easily be added as an option or is there a simple hack that would allow me the get a 2 digits ?

Thanks for any advises

Hugo

**Comment by bendrucker** [comment]
Glad you're enjoying it!

Months have been parsed to numbers (unlike a card number or a CVC they are truly numbers and a leading zero is insignificant) for quite a while. Not sure why this would only crop up recently for you. 

In any case, you can use [zero-fill](https://www.npmjs.com/package/zero-fill) on your data before sending it to Stripe.
