### ISSUE TITLE
Script cannot be minified with JSMin

### ISSUE THREAD

**Issue by joeserg** [bendrucker/angular-credit-cards#52]
Hey - this module is such a timesaver! I have noticed a slight issue with it though...

Attempting to minify release/angular-credit-cards.js with JSMin (via http://compressorrater.thruhere.net) results in this browser console error:

`Uncaught SyntaxError: Invalid flags supplied to RegExp constructor 'exports'`

The line in question is:

`var cvcRegex=/^\d{3,4}$/exports.isValid=function(cvc,type){if(typeof cvc!=='string')return false`

The minifier doesn't seem to understand where the regular expression ends and the next line starts.

Have you been able to produce a minified version that could be added to the repository?

Many thanks.

**Comment by bendrucker** [comment]
Thanks! Unfortunately I can't help here. That line comes from an upstream dependency. Though that dependency is mine, I'm not willing to change valid JavaScript and break my style rules to suit a particular minifier. UglifyJS definitely works.
