### ISSUE TITLE
change main in package.json (a compromise?)

### ISSUE THREAD

**Issue by robertbaker** [bendrucker/angular-credit-cards#55]
https://github.com/bendrucker/creditcards

This works fine in JSPM because here you have `"main": "index.js",`

and in your /index.js you export

```
'use strict'

exports.card = require('./src/card')
exports.cvc = require('./src/cvc')
exports.expiration = require('./src/expiration')
```

If you do the same for this repo. I won't need to use a fork, your 2 projects will be consistent (after all isn't that your argument?).

If you do this JSPM will be happy, browserify will be happy, and your 2 projects will be similar in that respect.

**Comment by bendrucker** [comment]
> your 2 projects will be consistent

It's not about 2, it's about a workflow that works everywhere: https://www.npmjs.com/~bendrucker

Per #54, I'll take a PR. I can't promise permanent compatibility because I write code that's compatible with Node/Browserify. That said, I'm not active working on angular-cc so it should be fine.

**Comment by robertbaker** [comment]
@bendrucker  see
https://github.com/robertbaker/angular-credit-cards/tree/jspm_fix
