### ISSUE TITLE
Unreproductable bug and pretty cool bootstrap markup

### ISSUE THREAD

**Issue by hugsbrugs** [bendrucker/angular-credit-cards#56]
Hi !

I was setting a codepen : 
<p data-height="268" data-theme-id="0" data-slug-hash="XbBZqL" data-default-tab="result" data-user="hugsbrugs" class='codepen'>See the Pen <a href='http://codepen.io/hugsbrugs/pen/XbBZqL/'>Angular Credit Card</a> by Hugo (<a href='http://codepen.io/hugsbrugs'>@hugsbrugs</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

to show you my bug : when I select with my keyboard month 01 and year 2016, the key/pair was wrong until I quit year selection, get back to it, select another year and get back to 2016 ... but this bug has disappeared on my pen ... I will go on further investigations ... because it's unbelievable !

But by the way, I wanted to share with you my bootstrap markup with mandatory fields (bootstrap warning class and validate form button deactivated until form is valid), valid (success class) and invalid (error class) and thanks to you and your Card Eager Type, the card type icon ! This could interest people who uses your plugin since it's almost production ready : let me know what you think about it ...

Cheers !

**Comment by bendrucker** [comment]
Thanks!
