### ISSUE TITLE
ccFormat bug when typing quickly

### ISSUE THREAD

**Issue by SimeonC** [bendrucker/angular-credit-cards#57]
I found that in certain situations (not in your demos for some reason) - more specifically when using angular-material which I think has many more watches/formatters/parsers on the input directive, I can end up with the cursor  ending up in the wrong place as it incorrectly tries to move my cursor around.

I found I fixed this issue by changing the $watch for the ccFormat to have the following if statement:
(Line 65 of number.js)
```js
if (formatted && (!formatted.charAt(selectionEnd - 1).trim() || formatted.length !== input.length)) {
```

Not sure if this will break things or not but it seemed to fix my issue.

**Comment by bendrucker** [comment]
Hmm. Not really sure what to do about this. Thanks for reporting it, but I'm not willing to add something like this without a better understanding of what's going on.

**Comment by SimeonC** [comment]
I think the issue was basically the watch doesn't fire immediately. So during typing the following is entered `"4111222|"`, then the watch fires and adds the spaces, but for some reason it decides my caret should be back one space so the end result is this `"4111 22|2"`. I also had the same issue using the backspace button as I'd end up skipping characters instead of spaces.

**Comment by bendrucker** [comment]
It fires asynchronously? If you can manage to send a PR that tests this I'm game.

**Comment by SimeonC** [comment]
I got it! It was the debounce effect - see here: http://plnkr.co/edit/PLZ6PqPc3cu0v9dqfnxW?p=preview

I ended up fixing it by replacing the actual watch with this:

```js
$element.on('input', function formatInput () {
          	var input = $element.val();
          	var previous = $viewValue();
            if (!input) return
            var element = $element[0]
            var formatted = card.format(card.parse(input))

            //ngModel.$setViewValue(formatted)
            var selectionEnd = element.selectionEnd
            $element.val(formatted);
            //ngModel.$render()
            if (formatted && (!formatted.charAt(selectionEnd - 1).trim())) {
              if (previous && previous.length < formatted.length) {
                selectionEnd++
              } else {
                selectionEnd--
              }
            }
            element.setSelectionRange(selectionEnd, selectionEnd)
          })
```

Basically this fires before any of the watchers/formatters/parsers so it can't be delayed or intercepted without hooking into the input event again.
