### ISSUE TITLE
Broken link in ReadMe?

### ISSUE THREAD

**Issue by NumEricR** [bendrucker/angular-credit-cards#58]
Hi,

I've noticed a broken link in README: see "Exposes the [card type](https://github.com/bendrucker/creditcards/blob/master/README.md#cardtypenumber---string) as `$ccType` on the model controller".
I think this link should use https://github.com/bendrucker/creditcards-types#card-types

**Comment by bendrucker** [comment]
Good catch, please submit a PR

**Comment by NumEricR** [comment]
I think you could do it faster than me! :wink:
You know I have to fork this project, commit, make the PR, ... and this is only to fix a link :confused:

**Comment by bendrucker** [comment]
Nope, you can make it happen faster. You can submit PRs via GitHub very easily.

**Comment by antoinepairet** [comment]
@NumEricR Just browse the source, click on the pencil in top right corner, perform the edit and submit the PR. Github will guide your through every step ;-)
