### ISSUE TITLE
Input pattern mismatches formatted CC number

### ISSUE THREAD

**Issue by nikcorg** [bendrucker/angular-credit-cards#61]
The validation pattern added to the credit card number input[1] fails the form validation when the number is formatted, since it then contains also white space.

Since the number is validated on the model, is there really a need for the input pattern as well? In any case, it should probably allow single whitespaces between number groups, or be specific to the detected card type.

[1] https://github.com/bendrucker/angular-credit-cards/blob/master/src/number.js#L17

**Comment by nikcorg** [comment]
If you like, I can produce a PR for dropping or modifying the regex.

**Comment by bendrucker** [comment]
Don't understand what you're referring to here, please send a PR

**Comment by nikcorg** [comment]
@bendrucker Sent, see #62.
