### ISSUE TITLE
Year onChange fail using select

### ISSUE THREAD

**Issue by jwilpin** [bendrucker/angular-credit-cards#63]
Hi, using select field in year, onChange fails when you use keydown (stay in month field, select one month, and then, tab key to year field and just keydown. 2015 to 2016 doesn´t call onchange at first time, 
neither validations or change of model occurs ). 

In order to reproduce this bug, I create this stage: http://plnkr.co/edit/FDtoRFrOUW8gKhOXfNgu?p=preview

Sincerely,

**Comment by bendrucker** [comment]
Sorry, I'm not actually doing anything here that would cause this. 99% sure this comes from Angular. If you can determine that it doesn't and can either send a PR or some research, I'd be happy to take a second look.
