### ISSUE TITLE
Credit Card Number Input Pattern and Whitespace

### ISSUE THREAD

**Issue by mpetito** [bendrucker/angular-credit-cards#64]
You have the following comment in your documentation:

> If you're using cc-format, you'll want to apply the novalidate attribute to disable native browser validation.

Is there a reason you couldn't just change the pattern you add to the input to be `[0-9 ]` so that browser validation passes the formatted card number?  I briefly tested this, and it seems to just work since your card number directive strips spaces that are input anyways.

**Comment by bendrucker** [comment]
Yes, there's a reason and I'll need thorough research to change it

See https://github.com/bendrucker/angular-credit-cards/pull/62#issuecomment-126428834 among other discussions

**Comment by mpetito** [comment]
If your concern is the keyboard that appears on mobile, I would suggest input type=tel, which should reliably change the input mode and allow for an expanded regex.

>... there are no default restrictions on valid values and by default browsers do no validation... If you need to enforce a specific syntax for acceptable phone number use the pattern attribute (RegEx validation).
http://www.wufoo.com/html5/types/2-tel.html

**Comment by bendrucker** [comment]
No, that doesn't show the exact same keyboard. If you can find a way to show the tel keyboard minus the hold/* keys the way the pattern hack does, I'd love to avoid the novalidate gotcha. But I've done plenty of research and thinking and will only change for clear documentation/research.
