### ISSUE TITLE
Card Number is Always Required

### ISSUE THREAD

**Issue by mpetito** [bendrucker/angular-credit-cards#65]
Your `ccNumber` and `ccNumberType` validators always fail if the card number is not specified.

Typically users would only expect this behavior if the `required` attribute (or ng-required) is in place, and then the validation error would be `required` (and not, for example, `ccNumber`, which should be reserved for an invalid card number instead of a missing card number).

I would suggest that your validators pass on empty inputs, e.g.:
        
       ngModel.$validators.ccNumber = function validateCcNumber (number) {
          return !number || card.isValid(number)
        }

        ngModel.$validators.ccNumberType = function validateCcNumberType (number) {
          return !number || card.isValid(number, $parse($attributes.ccType)($scope))
        }

**Comment by bendrucker** [comment]
Will take a PR
