### ISSUE TITLE
Expiration date (cc-exp) to work with one only input

### ISSUE THREAD

**Issue by jmvalencia** [bendrucker/angular-credit-cards#67]
It would be great if the expiration date validation works with one regular input, that may or not be masked by ##/##(##) without the need to have the full template the directive uses right now, I love this module but I would appreciate if this can be done, currently Im including additional code to accomplish this, @bendrucker thanks in advance for paying attention and your help.

Example:

![screen shot 2015-08-27 at 4 27 40 pm](https://cloud.githubusercontent.com/assets/1714452/9533583/97ffec1a-4cd8-11e5-84c1-bb8f516222c1.png)

**Comment by bendrucker** [comment]
Sorry, but this is way beyond the scope of what I can do right now, especially since I don't use Angular anymore. This is really tricky to get right and should be done in a separate package that's not coupled to Angular.

**Comment by twler** [comment]
I had the same request, and shut down just as quickly.  It's straightforward, and has as much reason to be "coupled to Angular" as anything else in the package...

My working code below in coffeescript, in case you're interested.

    module.directive "ccExpCombined", () ->
      restrict: 'A'
      require: ['ngModel']
      compile: ($element, $attributes) ->
        $attributes.$set 'maxlength', '7'
        ($scope, $element, $attributes, controllers) ->
          ngModel = controllers[0]
          $scope.$watch $attributes.ngModel, (date) ->
            return unless date
            backspace = date.slice(-2) is ' /' and date.slice(-3) isnt '/ /'
            date = if backspace then '' else date.replace /[^\d]/g, ''
            mm = date.substring 0,2
            yy = date.substring 2,4
            mm = '0' + mm[0] if mm in ['2','3','4','5','6','7','8','9']
            update = if backspace or !mm or mm in ['0','1'] then mm else mm + ' / ' + yy
            ngModel.$setViewValue update
            ngModel.$render()

![grab](https://cloud.githubusercontent.com/assets/819876/9972692/3f96d5b6-5e1c-11e5-9940-e6181c545652.gif)

**Comment by bendrucker** [comment]
I'll happily fix bugs but I'm not going to add new features here. That's why the engine is standalone ([creditcards](https://github.com/bendrucker/creditcards)).
