### ISSUE TITLE
Request cc-exp-combined

### ISSUE THREAD

**Issue by twler** [bendrucker/angular-credit-cards#71]
Would be nice to have built-in functionality to mimic the `MM / YY` simplicity like that found in Stripe's Checkout.  I have it working in my codebase, perhaps you can adapt to yours with es5, your custom parse methods, etc:

    module.directive "ccExpCombined", () ->
      restrict: 'A'
      require: ['ngModel']
      compile: ($element, $attributes) ->
        $attributes.$set 'maxlength', '7'
        ($scope, $element, $attributes, controllers) ->
          ngModel = controllers[0]
          $scope.$watch $attributes.ngModel, (date) ->
            return unless date
            backspace = date.slice(-2) is ' /' and date.slice(-3) isnt '/ /'
            date = if backspace then '' else date.replace /[^\d]/g, ''
            mm = date.substring 0,2
            yy = date.substring 2,4
            mm = '0' + mm[0] if mm in ['2','3','4','5','6','7','8','9']
            update = if backspace or !mm or mm in ['0','1'] then mm else mm + ' / ' + yy
            ngModel.$setViewValue update
            ngModel.$render()

![grab](https://cloud.githubusercontent.com/assets/819876/9972692/3f96d5b6-5e1c-11e5-9940-e6181c545652.gif)

**Comment by bendrucker** [comment]
https://github.com/bendrucker/angular-credit-cards/issues/67#issuecomment-135568602
