### ISSUE TITLE
cc-format novalidate does not insert spaces

### ISSUE THREAD

**Issue by leonbrag** [bendrucker/angular-credit-cards#73]
Hi,

I have added cc-format and novalidate to the original plunk (http://plnkr.co/edit/uE47aZ) like so:

           <input type="text" class="form-control" id="cardNumber" cc-number cc-format name="ccNumber" ng-model="card.number" novalidate>

however credit card input still does not cause spaces to show after groups of 4 digits is entered.

Am I doing something obviously wrong?
Thanks!

**Comment by bendrucker** [comment]
`novalidate` is only a valid attribute for `form` elements

**Comment by leonbrag** [comment]
Thanks. But even this does not cause 4 digit grouping (tested in IE10 and Edge on Win10):
 <input type="text" class="form-control" id="cardNumber" cc-number cc-format name="ccNumber" ng-model="card.number">
Sorry if this is something obvious.

**Comment by bendrucker** [comment]
Can you try a different browser?

**Comment by leonbrag** [comment]
Here is how input looks:

input type="text" class="form-control" id="cardNumber" cc-format cc-number name="ccNumber" ng-model="card.number"

Does not work in: 
1. Chrome  Version 46.0.2490.52 beta-m
2. IE 11
3. FF

Attached screen shot shows that cc-format is applied, yet number is not formatted.
![capture](https://cloud.githubusercontent.com/assets/5290089/10297366/b13f234a-6b86-11e5-8501-825b4d9210f9.PNG)

**Comment by bendrucker** [comment]
The version on the Plunkr is out of date
