### ISSUE TITLE
Credit Card Number input issue on Android device

### ISSUE THREAD

**Issue by vikramarka** [bendrucker/angular-credit-cards#74]
I observed that, the soft keyboard switches to alphabets side on each key press for card number input.

**Comment by vikramarka** [comment]
If I remove the cc-format, it is not switching to alphabet side.

**Comment by bendrucker** [comment]
That's unfortunate, but sadly I don't think there's anything I can do to change that

**Comment by grahamlittle** [comment]
you can set the format of the input field to "tel" and it will only show numbers on mobile devices i believe.

**Comment by bendrucker** [comment]
Yeah I believe that's your only option. Sucks that Android is incorrect in that respect and doesn't abide by the [numeric pattern](https://www.npmjs.com/package/numeric-pattern).
