### ISSUE TITLE
Suggestion: remove spaces from credit card type

### ISSUE THREAD

**Issue by leonbrag** [bendrucker/angular-credit-cards#75]
Hi,

It would be great to remove spaces in all detected card types:
Type('American Express' ....

Removing space would enable applying ng-class to an element:
ng-class="ccForm.ccNumber.$ccType"

or is there an easier way to get card type without a space in it?

Thanks

**Comment by bendrucker** [comment]
For now it's best to pass the names through a function to get them in whatever case you might need
