### ISSUE TITLE
Error injecting credit-cards dependency into the module

### ISSUE THREAD

**Issue by dasatti** [bendrucker/angular-credit-cards#76]
When injecting credit-cards dependency into the module following error is thrown

https://docs.angularjs.org/error/$injector/modulerr?p0=creo&p1=Error:%20%5B$injector:modulerr%5D%20http:%2F%2Ferrors.angularjs.org%2F1.4.2%2F$injector%2Fmodulerr%3Fp0%3Dcredit-cards%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.4.2%252F%2524injector%252Fnomod%253Fp0%253Dcredit-cards%250A%2520%2520%2520%2520at%2520Error%2520(native)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%252Fcreomob%252Fjs%252Fangular%252Fangular.min.js%253A6%253A416%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%252Fcreomob%252Fjs%252Fangular%252Fangular.min.js%253A24%253A66%250A%2520%2520%2520%2520at%2520a%2520(http%253A%252F%252Flocalhost%252Fcreomob%252Fjs%252Fangular%252Fangular.min.js%253A23%253A109)%250A%2520%2520%2520%2520at%2520P.bootstrap%2520(http%253A%252F%252Flocalhost%252Fcreomob%252Fjs%252Fangular%252Fangular.min.js%253A23%253A352)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%252Fcreomob%252Fjs%252Fangular%252Fangular.min.js%253A37%253A451%250A%2520%2520%2520%2520at%2520m%2520(http%253A%252F%252Flocalhost%252Fcreomob%252Fjs%252Fangular%252Fangular.min.js%253A7%253A322)%250A%2520%2520%2520%2520at%2520g%2520(http%253A%252F%252Flocalhost%252Fcreomob%252Fjs%252Fangular%252Fangular.min.js%253A37%253A229)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%252Fcreomob%252Fjs%252Fangular%252Fangular.min.js%253A37%253A398%250A%2520%2520%2520%2520at%2520m%2520(http%253A%252F%252Flocalhost%252Fcreomob%252Fjs%252Fangular%252Fangular.min.js%253A7%253A322)%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20http:%2F%2Flocalhost%2Fcreomob%2Fjs%2Fangular%2Fangular.min.js:6:416%0A%20%20%20%20at%20http:%2F%2Flocalhost%2Fcreomob%2Fjs%2Fangular%2Fangular.min.js:38:154%0A%20%20%20%20at%20m%20(http:%2F%2Flocalhost%2Fcreomob%2Fjs%2Fangular%2Fangular.min.js:7:322)%0A%20%20%20%20at%20g%20(http:%2F%2Flocalhost%2Fcreomob%2Fjs%2Fangular%2Fangular.min.js:37:229)%0A%20%20%20%20at%20http:%2F%2Flocalhost%2Fcreomob%2Fjs%2Fangular%2Fangular.min.js:37:398%0A%20%20%20%20at%20m%20(http:%2F%2Flocalhost%2Fcreomob%2Fjs%2Fangular%2Fangular.min.js:7:322)%0A%20%20%20%20at%20g%20(http:%2F%2Flocalhost%2Fcreomob%2Fjs%2Fangular%2Fangular.min.js:37:229)%0A%20%20%20%20at%20eb%20(http:%2F%2Flocalhost%2Fcreomob%2Fjs%2Fangular%2Fangular.min.js:40:503)%0A%20%20%20%20at%20d%20(http:%2F%2Flocalhost%2Fcreomob%2Fjs%2Fangular%2Fangular.min.js:19:339

Following is the code

var app = angular.module('app', ['ngRoute', 'angularSoap', 'ui.bootstrap',
        'ngSanitize', 'infinite-scroll','credit-cards']);

When I instead use following
var app = angular.module('app', ['ngRoute', 'angularSoap', 'ui.bootstrap',
        'ngSanitize', 'infinite-scroll',require('angular-credit-cards')]);

I get error "Uncaught ReferenceError: require is not defined"

**Comment by bendrucker** [comment]
Use the version in the release dir if you're using window globals
