### ISSUE TITLE
Question: change CVC placeholder from JS, when ccType resolved

### ISSUE THREAD

**Issue by leonbrag** [bendrucker/angular-credit-cards#78]
Hi,
Is this possible to detect/subscribe to the event when ccType becomes know in the JS, so I can change CVC placeholder (4 digit for amex, 3 for visa) as appropriate?
Use case: when visa is detected, cvc is set to ... ; when Amex is detected, CVC is set to ....

Thanks!

**Comment by bendrucker** [comment]
Sure, you can use `$scope.watch` for that
