### ISSUE TITLE
Position of Cursor after paste with cc-format enabled

### ISSUE THREAD

**Issue by grahamlittle** [bendrucker/angular-credit-cards#79]
Hi, 

<b>Demo of issue</b>:
http://plnkr.co/edit/M8JbO6

<b>Description of issue</b>:
As you can see in the demo plnkr which i have updated by enabling cc-format and also pointing at the latest version of 2.3.5, when you paste a credit card number into the input it positions the cursor 3 digits from the right rather than at the end.

<b>Steps to create issue</b>:
First paste: 4111111111111111

and you will observe the behaviour i described. 

Second paste: 4111 1111 1111 1111

If you paste a pre-formatted number then it will put the cursor at the end.

<b>Comments:</b>

It seems to me that the cc-format process is positioning the cursor based on the number of digits pasted but does not include the spaces when cc-format is applied. This behaviour is confirmed when cc-format is turned off and both variations of the numbers are pasted in, the cursor is at the end of the pasted number. Perhaps the use of .trim() in numbers.js line 67 might be the cause of this behaviour.

**Comment by bendrucker** [comment]
Yeah this gets pretty tricky -- it's off by the 3 spaces that are inserted. If you wanna take a crack at it I'd be happy to review a PR but otherwise I'd prefer to keep formatting simple even if it doesn't get 100% of input cases perfectly right.

**Comment by grahamlittle** [comment]
I think will have a crack, should have some spare time later on this week / next week and will submit a PR once its ready. thanks.
