### ISSUE TITLE
Resetting the Form

### ISSUE THREAD

**Issue by randdusing** [bendrucker/angular-credit-cards#81]
I'm still new to Angular so apologies if this is really basic or I'm using incorrect terminology.

I couldn't find this in the Angular form documentation, but how do I clear a form?

If I type a valid number in the number field, the value is "committed" to $scope.card and setting $scope.card = null clears the value from the form.

If I type an invalid number in the number field, the value isn't "committed" to $scope.card and setting $scope.card = null doesn't clear the incomplete value from the form since $scope.card is still null.

$scope.ccForm.$setPristine() changes the $pristine flag, but isn't actually clearing uncommitted values either.

**Comment by bendrucker** [comment]
You can use `$setViewValue` for model controllers to manually set the value to `''`

**Comment by randdusing** [comment]
Setting it to ``` '' ```  or ```null ```doesn't have an effect, but setting it to ``` ' '  ``` does. Feels a bit hacky, but it should work.
