### ISSUE TITLE
Android 4.3 problem with cc number field

### ISSUE THREAD

**Issue by sebrojas14** [bendrucker/angular-credit-cards#83]
In android 4.3, the cc number filed has a serious problem. When the user switch the keyboar to numbers and starts to type de credit card number. after 1 or 2 digits, the keybaord jumps to characteres mode, and then, afer manually swicth the keyboard and enter other digit, the same thing happens, so the user ends switchng the mode of the keyboar each time. Additionally, when a 0 is entered, the cursur moves before the 0, so if for exmaple the user was entering 05, ends up with 50! IS something related with webview version of androdi 4.3 (and maybe older veriosn, also I didn't test it in android 4.4) because in andorid 5 or using crosswalk in android 4.3, the error dissapears

**Comment by bendrucker** [comment]
Hmm, interesting. We do use this library at Eaze in Angular apps, but our primary support target on Android is Chrome. The fact that the issue isn't present on Android 5 or w/ Crosswalk means I won't be able to devote any company resources here. 

Is this with `cc-format` on? And if so, does everything work properly without it?

**Comment by bendrucker** [comment]
Sorry for the delayed response by the way. I know I've lapsed a bit on supporting this library.

**Comment by terrorhawks** [comment]
I'm having the same issue, we're using crosswalk. Issue found on Samsung Galaxy.

**Comment by winstef** [comment]
I'm having the same issue with Android 5 and crosswalk. When removing `cc-format` it seems to be working but it just doesn't trigger the numeric keyboard

**Comment by bendrucker** [comment]
Can somebody help me out here with screenshots or some additional detail? My time budget for working on this is pretty small. Help from someone who's experienced this and poked around at a solution is the only way it's going to get fixed.

**Comment by drKnoxy** [comment]
this cursor move problem is the same as #111
