### ISSUE TITLE
cc number length less than 16 be valid??

### ISSUE THREAD

**Issue by ulion** [bendrucker/angular-credit-cards#86]
Try 4222 2222 2222 2

It turns out $valid for this number, imo it should not.

**Comment by bendrucker** [comment]
It's valid, see https://github.com/bendrucker/creditcards-types for full definitions

**Comment by ulion** [comment]
Sorry, did not get it, please explain why an invalid credit number is valid?

**Comment by bendrucker** [comment]
https://en.wikipedia.org/wiki/Bank_card_number

**Comment by ulion** [comment]
get it, thx.
