### ISSUE TITLE
when using cc-format, you cant enter credit cards with more than 16 digits

### ISSUE THREAD

**Issue by syrianadus** [bendrucker/angular-credit-cards#90]
when using cc-format on input element for the purpose of formatting the card number, you cant enter more than 16 digits.
for example : trying to enter this Credit card number : 4917610000000000003 which is a valid visa-debit number, it will stop you at digit 16 and the actual output will be : 4917 6100 0000 0000. The expected output is : 4917 6100 0000 0000 003

**Comment by bendrucker** [comment]
Same deal as the previous, this will require credit-cards-types work. I'd also appreciate proof of some kind that 4x4 + 3 is the proper format.
