### ISSUE TITLE
npm install incomplete

### ISSUE THREAD

**Issue by nrice** [bendrucker/angular-credit-cards#93]
The npm  install does not create angular-credit-cards.js, the bower install does.

**Comment by bendrucker** [comment]
I don't publish built files to npm

**Comment by samvloeberghs** [comment]
aah this is the reason why I doesn't work on my side. I don't use bower. What's your reason not to publish build files to npm?

Bower has dropped development and I only use npm to manage dependencies as well as devDependencies.

**Comment by bendrucker** [comment]
I expect people using npm to use browserify or webpack. Committing built files is a huge pain especially when there are two great tools for js builds.

**Comment by samvloeberghs** [comment]
Ok but than your oppionating your code.. You are forcing people to use it. What if I don't want to use webpack or browserify but prefer something else? It might for example complefixy a simpel project I'm building.

The release is published in the bower version, why not on npm than.

**Comment by bendrucker** [comment]
I'm taking out build files altogether as well as bower support. Sorry but I have a lot of projects to maintain and this isn't something that I'm interested in negotiating.
