### ISSUE TITLE
Maestro card fails validation with valid number

### ISSUE THREAD

**Issue by grahamlittle** [bendrucker/angular-credit-cards#97]
Hi, 

I was away when a bug came up with the library and the team fixed it in a local version rather than submitting it to the project so i am submitting it here for review:

**Bug Description:**
A customer's Maestro card with number 6016 6070 9505 8666 was rejected although it is in the allowed numbers range. The requirement is to allow the range 500000-509999 560000-699999, but still to exclude the range for cards issued by Discover:
601100 - 601109
601120 - 601149
601174 - 601174
601177 - 601179
601186 - 601199
644000 - 649999
650000 - 659999
This is specified in the "Maestro Internationally Issued" column in [bin_rules.pdf](https://github.com/bendrucker/angular-credit-cards/files/121414/bin_rules.pdf).
The following site can be used to generate / verify test data:
http://www.freeformatter.com/credit-card-number-generator-validator.html

In the current version of the library, Discover cards are correctly recognised as invalid. So the fix should preserve this rule.

**Bug Resolution:**

In order to rectify the problem the team change the pattern for maestro as described below to allow the correct ranges to work

line 157 angular-credit-cards.js 
changed to 
pattern: /^(?:5[06789]\d\d|(?!60110)(?!6011[234])(?!60117[4789])(?!60118[6789])(?!60119)(?!64[456789])(?!65)6\d\d\d)\d{8,15}$/,

from 
pattern: /^(?:5[0678]\d\d|6304|6390|67\d\d)\d{8,15}$/,

I look forward to hearing back from you about whether this is an acceptable change or if you have other suggestions.

Best Wishes

Graham

**Comment by bendrucker** [comment]
Done!

**Comment by grahamlittle** [comment]
awesome thanks a lot @bendrucker
