### ISSUE TITLE
Build failing?

### ISSUE THREAD

**Issue by foucdeg** [bendrucker/angular-credit-cards#98]
The build for master is currently failing. Since your last commit dates back from a few days ago, I thought maybe you hadn't noticed?
Due to that (I believe), npm still considers the previous version as the latest. Do you know when version 2.4.3 will be live?
Thanks

**Comment by ryekerjh** [comment]
I am having trouble with build as well. Throwing module not available

**Comment by bendrucker** [comment]
Was just a weird Phantom issue, bumping to 2.0 fixed it. Not sure what happened w/ 2.4.3 but it's published now.
