### ISSUE TITLE
Cannot validate expiration with prefilled/existing model data

### ISSUE THREAD

**Issue by eternalwaves** [bendrucker/angular-credit-cards#99]
For ease of development, I'm using the same form for both adding and editing an existing credit card. What I've found is that I can have an expiration date of 05/17, for example, and typing in either a 1- or 2-digit month and a 2-digit year works. But when prepopulating the form with an existing model, both fields have to be retyped manually, or else both are considered invalid.

Demo here: http://plnkr.co/edit/bsNO7wxqjFOcYtQrKcEe?p=preview

Even though ccExp validates, having ccExpMonth and ccExpYear invalid makes the entire form invalid.

**Comment by bendrucker** [comment]
PR would be appreciated, even if it's just failing tests

**Comment by eternalwaves** [comment]
Don't have the time to put it together. I'm reporting so the issue is made known and someone can work on it.

**Comment by bendrucker** [comment]
Sorry for not looking closer initially. The issue was that your example data was invalid:

```js
$scope.card = {
    expiration: {
      month: '5',
      year: '2017'
    }
  };
```

The `month` and `year` must be numbers.
